title: pacPrism
description: A semi-decentralized package distribution system for Debian GNU/Linux
baseurl: ""
url: "https://pacprism.github.io"
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
lang: en
author: pacPrism Team

# Social links
github_username: tzbkk

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/